# Generated by Django 5.2.1 on 2025-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.CharField(max_length=120),
        ),
    ]
