# Generated by Django 5.2.1 on 2025-05-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_created_at_alter_content_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
